### ISSUE TITLE
[BUG] Application End Date Not Calculating From Correct End Date

### ISSUE THREAD

**Issue by codingshot** [PotLock/bos-app#223]
Currently calculated form end of matching round
should be 7 days to apply

- check if matching round tags are correctly calculating

<img width="1090" alt="" src="https://github.com/PotLock/bos-app/assets/45281667/a7b30253-8127-41b4-9f55-ce904e4b6fff">

**Comment by lachlanglen** [comment]
Closed by https://github.com/PotLock/bos-app/pull/224
