### ISSUE TITLE
[BUG]  Form Cleaning (Trim Whitespace) and Https Validation for Link on Create Proejct

### ISSUE THREAD

**Issue by codingshot** [PotLock/bos-app#258]
And there remains the website bug - look at our website link. All the web dev has to do, is add "https://" to the link submitted. It's a flaw on the form submission side, not the user

Also the github link has an error from a space there. Simple form cleaning / checking upon submission can trim whitespace around form entries

-----------

**Comment by lachlanglen** [comment]
Closed by https://github.com/PotLock/bos-app/commit/2775f9d37885767293ff5c21249af76e08aa666e
