### ISSUE TITLE
[BUG]  Random DOnations pulling from all projects onr egistry instead of just approved

### ISSUE THREAD

**Issue by codingshot** [PotLock/bos-app#259]
- make sure it also is the case for admins as well

--------
https://github.com/PotLock/bos-app/blob/a5780f1953a03d7442113261fc69c2a9a9eb94f8/apps/potlock/widget/Project/ListPage.jsx#L102

https://github.com/PotLock/bos-app/blob/a5780f1953a03d7442113261fc69c2a9a9eb94f8/apps/potlock/widget/Project/ModalDonation.jsx#L11

Looks like just getting all registered projects from props and then randomly choosing an index on here

**Comment by lachlanglen** [comment]
Closed by https://github.com/PotLock/bos-app/commit/308c7d75aa4d70e837201b5995c651f9c9868838
