### ISSUE TITLE
[BUG] On Pot Page Show Donations Number Instead of Unique Donors

### ISSUE THREAD

**Issue by codingshot** [PotLock/bos-app#285]
**Describe the bug**
On pot page details
- should show number of unique donors but currently is showing number of donations
- should show donations is text fix
- but really prefer unique donors as donations is on donations apge

![](https://github.com/PotLock/bos-app/assets/45281667/022ebc7e-e117-4e75-8c6b-761184353a52)

**Comment by lachlanglen** [comment]
Closed by #290
