### ISSUE TITLE
🟧 Round Manager Dashboard | My Rounds / My Pots - DUPLICATE

### ISSUE THREAD

**Issue by codingshot** [PotLock/bos-app#39]
# Problem
Round managers need to query dashboards to see rounds they are admins for 
# User Story(s):
 As a _______, I want to ____, so that I can

# Description
Description of solution

# Acceptance Criteria
Outline what needs to be done

# Limitations 
Outline any potential limitations
# Resources
- outline links and relevant resources, references implementations

**Comment by lachlanglen** [comment]
@codingshot isn't this a duplicate of https://github.com/PotLock/bos-app/issues/43?

**Comment by lachlanglen** [comment]
closing as duplicate
