### ISSUE TITLE
Donor Checkout Page

### ISSUE THREAD

**Issue by codingshot** [PotLock/bos-app#40]
# Problem
Instead of paying directly donation buy donation, donors and verified humans should be able to put all their items in a cart, remove and edit this cart, and payout at once. 
# User Story(s):
- As a support I want to have a cart where I can view , Ability to have a cart where an amount ee
If in funding people should see estimated amount
- As a supporter, I want to see a QF calculator built in as tooling across all relevant donation pages so I can accurately estimate and understand the distribution of my funds. [QF-CALCULATOR]

# Description
Create a cart view where users can see both simple donations and quadratic matched donations for active rounts. 
# Acceptance Criteria
View
- view simple donations
- view quadratic funding donations
- display total
- display whether their is enough funding
- show base currency
- link to onramp solutions to top up cart if not enough
- if round match period is over than gray out transaction and say round is over
Quadratic funding calculation
- See how much a project will be matched and total matching power
- tool tip mentioning that this calculation is not finalized till the end of the found
Edit Cart
- Remove item from cart
- Adjust donation amount
Checkout
- show total amount
- show gas estimation in NEAR (adjust based on what is in cart / dynamic calculation)
- gray out checkout if not enough balance
- show someones balance
- if someone has enough balance but not in correct currency then trigger swap (not relevant / nice to have since MVP will be in just NEAR)

# Limitations 
- quadratic funding calculation might need to be separated
- adding cart from multiple contracts may confuse things
# Resources

![Image](https://github.com/PotLock/bos-app/assets/45281667/edcf2871-a40a-462c-99aa-eaaac8c84648)

**Comment by lachlanglen** [comment]
@codingshot this specific to pot donations, right? not direct donations?
