### ISSUE TITLE
[BUG]  Remove Admin on Deploy Pot Not Working

### ISSUE THREAD

**Issue by codingshot** [PotLock/bos-app#466]
**Describe the bug**

**To Reproduce**
1. Go to deploy pot
2. Click on 'add admin
3. Add admin
4. Try to remove admin

**Expected behavior**
THat admin to be removed (this is not edit settings)

Actually just an ui issue

<img width="828" alt="" src="https://github.com/PotLock/bos-app/assets/45281667/0c8eb97c-889c-43f4-a329-abeafd6b2e6f">
<img width="835" alt="" src="https://github.com/PotLock/bos-app/assets/45281667/44f5d8c3-7a90-4431-8e0d-fb372e1589ff">
<img width="519" alt="" src="https://github.com/PotLock/bos-app/assets/45281667/29a42d67-c000-4982-a6ab-e8ed76a1a51c">

**Comment by M-Rb3** [comment]
@lachlanglen 
![Image](https://github.com/PotLock/bos-app/assets/68287884/c8879a66-d57e-4e94-85af-f0307cccef8d)
![Image](https://github.com/PotLock/bos-app/assets/68287884/d15acd4c-8391-422e-bf6e-f30ec876ab09)
