### ISSUE TITLE
Create PotLock Styled Components Kit

### ISSUE THREAD

**Issue by codingshot** [PotLock/bos-app#5]
# Problem
Need a styled component library so people can easily fork and we can rapidly development components
# User Story:
 As a developer, I want to create PotLock styled components, so that I can rapidy prototype

# Description
A set of buttons, styled componened kits to rapidly prototype bos components without repeating code
# Acceptance Criteria
Outline what needs to be done

# Limitations 
- Dependent on a designer
# Resources
- outline links and relevant resources, references implementations
- Examples of Styled Component Kits
- [ ] https://www.boshacks.com/#/nomination.ndctools.near/widget/NDC.StyledComponents
- [ ] https://www.boshacks.com/#/nearui.near/widget/index

**Comment by lachlanglen** [comment]
@codingshot we pretty much have this - all inputs, buttons, donations info etc are componentized

The code needs some cleaning up but that's a separate ticket.
