### ISSUE TITLE
Change Project Status | ReFi Council / Admin

### ISSUE THREAD

**Issue by codingshot** [PotLock/bos-app#50]
# Problem
Currently there is no view for admins to flag or block projects in the project registry (projects are on the whitelist bby default). thies means although their is fee associated if we subsdizie this then they could spam our registry.
# User Story(s):
 As a ReFi Council or Admin, I want to be able to have a dashboard for changing project status, so that I can prevent for spam from showing on PotLock
As a ReFi Council or admin, I want to be able to see a unfilter project registry, so i can change the status

# Description
A simple dashboard that shows projects in project registry and proposes to change status. 
# Acceptance Criteria
For admins
- a view of project registry that is unfilters
Project filter page
- see past changes
- see projects added through signup (by admin or council
- see project flagged
- filter based on project status
On a Project Page
- If admin or council member, ability to propose to change project status 
- drop down for graylist and spam list

# Limitations 
- maybe a button in existing project registry
- maybe need a reason to change
# Resources
- Registry Contract Information https://github.com/PotLock/core/issues/3

![Image](https://github.com/PotLock/bos-app/assets/45281667/0436d534-1587-45ef-8be0-d8cb5c6ae607)

**Comment by lachlanglen** [comment]
Resolved in https://github.com/PotLock/bos-app/commit/575625819cb561d63edc9522369f8710d2a75748
