### ISSUE TITLE
[BUG] Registry Requirements Not Showing on Pot Settings

### ISSUE THREAD

**Issue by codingshot** [PotLock/bos-app#527]
**Describe the bug**
Registry requirement (which list contract and list id) should show -> deprecate version should show registry.potlock.near
**To Reproduce**
1. Go to nearian pot
2. Click on settings https://bos.potlock.org/?tab=pot&potId=nearian.v1.potfactory.potlock.near&nav=settings
<img width="1137" alt="" src="https://github.com/PotLock/bos-app/assets/45281667/24a20266-e4a2-43aa-8aa4-cceb587e4edf">

**Expected behavior**
Show a row with application requirements and show which contract
**Screenshots**

**Comment by lachlanglen** [comment]
@M-Rb3 Could you add an additional row that says "Registry Provider" and then "<contract_name>: <method_name>" e.g. "lists.potlock.near: is_registered"

this is not super high priority; helping @wpdas with the Além refactor is more important, if you can find a minute to slip this in somewhere over the coming week that would be helpful.
