### ISSUE TITLE
[FEATURE] For No Registry Required Pots, Make Create Project and Apply to Pot the Same Flow

### ISSUE THREAD

**Issue by codingshot** [PotLock/bos-app#556]
# Problem
People are submitting empty projects and having a 2 part step for applying to pot

# Description
- make it so create project also applies to project
- make it so that if not required register project on public goods registry they still need ot have a full profile
- in future different lists will apply to for reelvant official lists as well

**Comment by lachlanglen** [comment]
Closing as is a duplicate of https://github.com/PotLock/bos-app-alem/issues/52
