### ISSUE TITLE
Emtpy team members cannot be removed

### ISSUE THREAD

**Issue by ssplashh** [PotLock/bos-app#69]
**Describe the bug**
Removing team members doesn't work

**To Reproduce**
1. Go to https://near.social/potlock.near/widget/Index
2. Click on https://near.social/potlock.near/widget/Index?tab=project&projectId=daoashe.near
3. Scroll down to 'edit profile' and remove empty members
4. Afterafter removing the empty team members, saving the changes and paying gas the empty team members show again.

**Expected behavior**
It should show only the team members I've added.

**Screenshots**
Please, review attached.
![members 2](https://github.com/PotLock/bos-app/assets/128165996/9eb1f451-93c6-47f7-b4b3-3ad47f8a78d0)
![members 1](https://github.com/PotLock/bos-app/assets/128165996/e2a52e67-4892-4579-985f-554573114a7d)

**Desktop (please complete the following information):**
 - OS:  Windows 10 Pro
 - Browser Chrome
 - Version [118.0.5993.118 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**
 - Device: Android
 - Browser Edge and Chrome

**Comment by lachlanglen** [comment]
@ssplashh thanks for reporting! this has been resolved, please give it a shot and lmk if you have any further issues!

**Comment by ssplashh** [comment]
Yes, it works now, thank you!

Best wishes,

Paloma
________________________________
De: Lachlan Glen ***@***.***>
Enviado: viernes, 3 de noviembre de 2023 19:32
Para: PotLock/bos-app ***@***.***>
Cc: Paloma Etienne ***@***.***>; Mention ***@***.***>
Asunto: Re: [PotLock/bos-app] Emtpy team members cannot be removed (Issue #69)


@ssplashh<https://github.com/ssplashh> thanks for reporting! this has been resolved, please give it a shot and lmk if you have any further issues!
