### ISSUE TITLE
Follow button on Project Profile overestimating gas

### ISSUE THREAD

**Issue by codingshot** [PotLock/bos-app#73]
**Describe the bug**

**To Reproduce**
<img width="857" alt="" src="https://github.com/PotLock/bos-app/assets/45281667/7458c3f7-e511-4aa8-9ee7-caee38779610">

1. Go to a project page and click follow

**Expected behavior**
- should be for way less to follow
<img width="806" alt="" src="https://github.com/PotLock/bos-app/assets/45281667/073f13bf-35af-4cd5-9001-3bb376a45af0">

**Comment by lachlanglen** [comment]
Resolved in https://github.com/PotLock/bos-app/commit/dba513cc37ce500bf1a231889149e17d21b12a65
