### ISSUE TITLE
Need to Scroll On Shopping Cart

### ISSUE THREAD

**Issue by codingshot** [PotLock/bos-app#77]
**Describe the bug**
If you add to many things to cart cannot scrolls
**To Reproduce**
1. Add projects to cart (more than 4)
2. Cannot find continue to cart
3. 
**Expected behavior**
Should have scroll on this
**Screenshots**
<img width="499" alt="" src="https://github.com/PotLock/bos-app/assets/45281667/ba627597-3344-498f-84c8-28995d11671d">

**Comment by lachlanglen** [comment]
Fixed in https://github.com/PotLock/bos-app/commit/b1530a988aac83673410188fdf544a3099cdf3f0
