### ISSUE TITLE
Add A Not-Audited Banner

### ISSUE THREAD

**Issue by codingshot** [PotLock/bos-app#78]
# Problem
People don't realize the project is not audited and are experiencing issues with donations
# User Story(s):
As a donor, I want to know if proejct is not audited

# Description
This app is in beta. It has not been audited. [Learn more](https://docs.potlock.io/audit)

# Acceptance Criteria
a banner
- learn more links to https://docs.potlock.io/general-information/beta-phase
- put in red potlock color

# Resources
- Reference version of this on https://tickets.opact.io/

<img width="1440" alt="" src="https://github.com/PotLock/bos-app/assets/45281667/1aec9e34-575f-4c20-9887-524ff767aac8">

**Comment by lachlanglen** [comment]
Closed by https://github.com/PotLock/bos-app/commit/b580289fcebe5804f7e38cfc8d640408b9ea0d7d
